### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by vanbilt** [shaunluttin/aurelia-open-id-connect#11]
The first two commands run successfully.
```
$ git clone https://github.com/shaunluttin/aurelia-open-id-connect.git
$ cd aurelia-open-id-connect/demo
```

Then I try to `npm install` and I get the following error: 
```
User@DESKTOP MINGW64 /c/code/aurelia-open-id-connect/demo (master)
$ npm install -y
npm ERR! addLocal Could not install C:\_forks\cli
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-y"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! path C:\_forks\cli
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\_forks\cli'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\_forks\cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\aurelia-open-id-connect\demo\npm-debug.log
```

I then try to run `npm run` and get the following error:
```
$ npm run demo

> aurelia-open-id-connect-demo@0.2.0 demo C:\code\aurelia-open-id-connect\demo
> au run --watch --env dev

Invalid Command: run
```

**Comment by shaunluttin** [comment]
Apologies for the bug. That was my mistake for pushing while still referencing a local fork of the aurelia-cli.

**Comment by shaunluttin** [comment]
Try checking out tag `0.11.2` first via `git checkout 0.11.2` because that is a more reliable release. 

    git clone https://github.com/shaunluttin/aurelia-open-id-connect.git
    git checkout 0.11.2
    cd aurelia-open-id-connect/demo
    npm install -y
    npm run demo

**Comment by vanbilt** [comment]
@shaunluttin - Thank You! That does indeed allow me to run the demo. 

I'm having other issues with trying to get a "fresh" install of `aurelia-open-id-connect` to work - there seem to be issues with `oidc-client` expecting more or fewer params - I have not tracked it all down yet - but with the demo running now I'm certain that I will be able to get my project running now. 

Thanks again!

**Comment by vanbilt** [comment]
Thank you for your help. I've got my local version up and running almost all the way through the full authorization cycle. I'm closing this as your solution solved my issue.

**Comment by shaunluttin** [comment]
That's excellent to hear @vanbilt. Thank you for opening and then updating the issue.

**Comment by shaunluttin** [comment]
@vanbilt Time permitting, I'd be interested to know whether release `0.11.4` works with your setup.

**Comment by vanbilt** [comment]
Hi Shaun,

If what you were requesting I do was the same steps as above but changing the `git checkout` step:
```
//...
git checkout 0.11.4
npm install -y
//...
```

Then the answer is yes, `0.11.4` works for me. If that is not what you meant, please let me know, I'd be more than happy to try other things as well.

**Comment by shaunluttin** [comment]
@vanbilt Yes. That is what I meant. Thank you for testing. 

It is a better release, because it builds directly from TypeScript to ES5 instead of using babel as an intermediary, and it also has better source mapping in Chrome, in my opinion. 

Also, pull requests are most welcome, if you find the time to doing any fixes, chores, or feature additions to the code.
