### ISSUE TITLE
Demo Resource servers not set up properly

### ISSUE THREAD

**Issue by Kukks** [shaunluttin/aurelia-open-id-connect#16]
The resource return errors regarding to CORS not being set up correctly.

`Fetch API cannot load https://zamboni-resource-01.azurewebsites.net/api/private. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://zamboni-app.azurewebsites.net' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by shaunluttin** [comment]
Thank you for the bug report. 

This is resolved now. We needed 1. to properly configure CORS and 2. not to hash the client secret twice.
