### ISSUE TITLE
Not all files are correctly packed in vendor-bundle

### ISSUE THREAD

**Issue by AndreSteenbergen** [shaunluttin/aurelia-open-id-connect#19]
In Aurelia CLI the following files don't get packed in vendor-bundle.js

When I open the network tab I see these files that don't get opened from vendor-bundle:
```
http://localhost:9000/node_modules/aurelia-open-id-connect/dist/amd/open-id-connect-user-block.js
http://localhost:9000/node_modules/aurelia-open-id-connect/dist/amd/open-id-connect-role-filter.js
http://localhost:9000/node_modules/aurelia-open-id-connect/dist/amd/open-id-connect-user-block.html
```

This is in my aurelia.json
```
{
            "name": "aurelia-open-id-connect",
            "path": "../node_modules/aurelia-open-id-connect/dist/amd",
            "main": "index"
          },
          "oidc-client"
```

**Comment by SystemAcc0unt** [comment]
I am having the same issue using webpack.

**Comment by shaunluttin** [comment]
Thank you for the issue. I'm planning to resume work on this later this year and will attempt to resolve it.

**Comment by nmocruz** [comment]
for webpack we need to add this to the plugin list
 ```
 new ModuleDependenciesPlugin({            
            "aurelia-open-id-connect": ["./open-id-connect-user-block", "./open-id-connect-role-filter"]
   }),
```
because I'm using the asp spa template, I'm puting in the ...vendor.js

**Comment by shaunluttin** [comment]
Duplicate: https://github.com/shaunluttin/aurelia-open-id-connect/issues/9
