### ISSUE TITLE
Global Resources defined in plugin not found in bundle

### ISSUE THREAD

**Issue by jonathaneckman** [shaunluttin/aurelia-open-id-connect#21]
Bundling with webpack I get the following errors:

> Error: Cannot find module './aurelia-open-id-connect/open-id-connect-user-block'.
> Error: Cannot find module './aurelia-open-id-connect/open-id-connect-role-filter'.

This is coming from plugin.ts

```
config.globalResources([
    "./open-id-connect-user-block",
    "./open-id-connect-role-filter",
])
```

**Comment by ghidello** [comment]
Using the webpack plugin v2.0 (I started learning webpack from this version so I don't know about the previous one) you can solve the issue specifying the plugin dependencies in your webpack.config.js throught the [ModuleDependenciesPlugin](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies#moduledependenciesplugin):

```javascript
plugins: [
      new AureliaPlugin(),
      new ModuleDependenciesPlugin({
          "aurelia-open-id-connect": ["./open-id-connect-user-block", "./open-id-connect-role-filter" ]
      })
  ]
```

**Comment by shaunluttin** [comment]
Duplicate: https://github.com/shaunluttin/aurelia-open-id-connect/issues/9
