### ISSUE TITLE
Problem with redirect url

### ISSUE THREAD

**Issue by stuartbloom** [shaunluttin/aurelia-open-id-connect#22]
Hi there, and firstly, thank you for the plugin; I am slowly making progress.

The thing I am unsure of is, What do i need to do in order to receive the token.  leaving things as they are, on successful login and redirect i get the following error: `ERROR [app-router] Error: Route not found: /signin-oidcid_token` along with my token.  Am I doing anything wrong?

Thanks in advance

**Comment by stuartbloom** [comment]
Got it working not an issue :)

**Comment by dijkpim** [comment]
I have the same error. Please can you explain how you got it working? ERROR [app-router] Error: Route not found: /signin-oidcid_token=eyJhbGciOiJSUzI1NiI.......
