### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by stuartbloom** [shaunluttin/aurelia-open-id-connect#25]
Hi there, and thank you for this plugin.

Although I am getting compilation errors when running the cloned demo, I am able to get it to connect ot my token server and make api calls :)

Just wondering; is it possible to use the plugin and forward the application to the token server when the application starts?

Thanks again

**Comment by shaunluttin** [comment]
Yes, that would be possible.

**Comment by stuartbloom** [comment]
@shaunluttin Thant's great, would you have an example?

**Comment by shaunluttin** [comment]
Hmm. I don't have an example of that off the top of my head. I've been away from this project for some time now. We can chat about it in this issue. On application startup, to forward the app to the authorization service, you will need to trigger this: 

https://github.com/shaunluttin/aurelia-open-id-connect/blob/master/src/open-id-connect-navigation-strategies.ts#L15-L18

```
    public login(instruction: NavigationInstruction): Promise<any> {
        let args: any = {};
        return this.userManager.signinRedirect(args);
    }
```

**Comment by stuartbloom** [comment]
Thanks, away from desk at the moment, but will have a play after the weekend, have a good one ;)

**Comment by AndreSteenbergen** [comment]
Something like this?

```
import { inject } from 'aurelia-dependency-injection';
import oidcConfig from "./open-id-connect-configuration";
import { OpenIdConnect, OpenIdConnectRoles } from "aurelia-open-id-connect";

@inject(OpenIdConnect)
export class App {
    constructor(openIdConnect) {
        let self = this;
        this.openIdConnect = openIdConnect;

        let mgr = self.openIdConnect.userManager;
        self.openIdConnect.userManager.getUser().then((user) => {
            if (user) {
                mgr.querySessionStatus().then(
                    function () {
                        self._loadUserDetails(user);
                    },
                    function () {
                        mgr.removeUser();
                    }
                );
            }
            else {
                mgr.signinSilent().then(function (user) {
                    self._loadUserDetails(user);
                }, function () {
                    mgr.signinRedirect({});
                });
            }
        });

        self.openIdConnect.userManager.events.addUserLoaded(() => {
            self.openIdConnect.userManager.getUser().then((user) => {
                self._loadUserDetails(user);
            });
        });
    }

    _loadUserDetails(user) {
        this.user = user;
    }
```

**Comment by shaunluttin** [comment]
Thank @AndreSteenbergen for that.

**Comment by AndreSteenbergen** [comment]
You're welcome

Op 7 jun. 2017 19:38 schreef "Shaun Luttin" <notifications@github.com>:
