### ISSUE TITLE
redirect_url to moduleid is not working

### ISSUE THREAD

**Issue by chdev77** [shaunluttin/aurelia-open-id-connect#26]
Everything is working except the redirect after logging in.

Here is my partial config.
```
export const oidcConfig = {
    loginRedirectModuleId: "**appmain**",
    logoutRedirectModuleId: "home",
    userManagerSettings: {
        // number of seconds in advance of access token expiry
        // to raise the access token expiring event
        accessTokenExpiringNotificationTime: 1,
        authority: environment.openidConfig.urls.authority,
        automaticSilentRenew: false, // true,
        //interval in milliseconds to check the user's session
        checkSessionInterval: 10000,
        client_id: environment.openidConfig.client_id,
        filterProtocolClaims: true,
        loadUserInfo: false,
        post_logout_redirect_uri: `${environment.openidConfig.urls.host}/signout-oidc`,
        redirect_uri: `${environment.openidConfig.urls.host}/signin-oidc`,
```

After signing in i get redirected correctly to 
`http://localhost:9000/signin-oidc#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodH.....`

Aurelia gives me this error in on the **appMain** route.
![capture](https://cloud.githubusercontent.com/assets/7691322/24720453/ce9a9b64-1a02-11e7-95c4-d8699f66cbae.PNG)

**Comment by chdev77** [comment]
I dissected the source code and was able to find the issue.

**Comment by shaunluttin** [comment]
I'm glad that you have solved the issue. Thank you for opening it and apologies for my late reply.
