### ISSUE TITLE
Enhancement: redirect to the module after login/ logout

### ISSUE THREAD

**Issue by AndreSteenbergen** [shaunluttin/aurelia-open-id-connect#27]
After login/ logout the user ends up at a url that is not very nice. I added this in app.js, to remove the url

```
eventAggregator.subscribe('router:navigation:complete', response => {
            if (response.instruction.fragment.indexOf(oidcConfig.redirect_route) > -1) {
                history.pushState({}, "Welcome back", "");
            }
        });
```

But it would be a great enhancement if the app autoredirects to the correct url, or make it optional.

**Comment by shaunluttin** [comment]
Possible duplicate: https://github.com/shaunluttin/aurelia-open-id-connect/issues/17

**Comment by AndreSteenbergen** [comment]
Looks like it yes ... I'll close
