### ISSUE TITLE
cannot install the package via jspm

### ISSUE THREAD

**Issue by lucamorelli** [shaunluttin/aurelia-open-id-connect#3]
I'm trying to add this package via jspm to an aurelia project that uses jspm, but the package is not installed completely in the jspm_packages, and when I run it I obtain the error message

jection (SystemJS) XHR error (500 Internal Server Error) loading http://localhost:5000/jspm_packages/github/shaunluttin/aurelia-open-id-connect@0.8.0.js
    Error: XHR error (500 Internal Server Error) loading http://localhost:5000/jspm_packages/github/shaunluttin/aurelia-open-id-connect@0.8.0.js
    Error loading http://localhost:5000/jspm_packages/github/shaunluttin/aurelia-open-id-connect@0.8.0.js

**Comment by shaunluttin** [comment]
@lucamorelli Thank you for that note. I will take a look in the next few days.

**Comment by lucamorelli** [comment]
Hmm... I don't know. I suppose is something related to the module configuration. I see that in the jspm/module directory I don't find the usual package@version.js file

**Comment by shaunluttin** [comment]
I just installed it like this: 

    jspm install github:shaunluttin/aurelia-open-id-connect@0.8.0

Which resulted in this: 

    jspm_packages
        github
            shaunluttin
                aurelia-open-id-connect@0.8.0
                    dist
                        amd 
                            index.js

How did you install it?

**Comment by shaunluttin** [comment]
Did you add it to your bundles?

**Comment by shaunluttin** [comment]
Fixed with version 0.9.0. 

    jspm install github:shaunluttin/aurelia-open-id-connect@0.9.0

Please let me know whether it works or not.

**Comment by shaunluttin** [comment]
@lucamorelli Does version 0.9.1 work for you?
