### ISSUE TITLE
OIDC on Aurelia SpaTemplates

### ISSUE THREAD

**Issue by andreabaldin** [shaunluttin/aurelia-open-id-connect#31]
I would like to integrate OIDC onto the Aurelia Microsoft.AspNetCore.SpaTemplates...  
Currently I'm getting  "Uncaught (in promise) Error: Unable to find module with ID: aurelia-open-id-connect".

**Comment by jblackburn21** [comment]
I had to do this to get it working with webpack:

1. Use PLATFORM.moduleName when adding the plugin:
.plugin(PLATFORM.moduleName('aurelia-open-id-connect'), (callback) => callback(oidcConfig))

2. add this to the webpack.config.js:
new ModuleDependenciesPlugin({
      'aurelia-open-id-connect': ['./open-id-connect-user-block', './open-id-connect-role-filter']
    }),

**Comment by shaunluttin** [comment]
I am working on adding some reliable demo applications here: 

https://github.com/shaunluttin/aurelia-open-id-connect-demos

That might be helpful for you.

**Comment by shaunluttin** [comment]
Thank you for your note. That will help as I setup support for Webpack and add a demo for the ASP.NET Core Aurelia SPA template.

**Comment by shaunluttin** [comment]
There is now a demo (from @gerbendekker) of the ASP.NET Core Aurelia SPA template here: 

https://github.com/shaunluttin/aurelia-open-id-connect-demos/tree/master/aurelia-app-identity-server-aspnetcore
