### ISSUE TITLE
Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by bewl** [shaunluttin/aurelia-open-id-connect#4]
When logged into Identity server, the aurelia client application is throwing an error approximately every 2 seconds:

`oidc-client.min.js:75 Uncaught TypeError: Cannot read property 'postMessage' of null`

**Comment by shaunluttin** [comment]
Let me see if I understand correct. You were able to run `shaunluttin/aurelia-open-id-connect`. Further, you were able to login to an IdentityServer. Then, something was throwing that error. Is that right?

**Comment by bewl** [comment]
Yes that is correct. While being authenticated inside of the application, the error occurs on a 2 second interval

**Comment by shaunluttin** [comment]
I've posted a related issue here: https://github.com/IdentityModel/oidc-client-js/issues/134

**Comment by shaunluttin** [comment]
@bewl I've marked this as an enhancement, because my sense is that this is a feature of the oidc-client-js that this adapter does not yet support.

**Comment by mttmccb** [comment]
Just bumped into this issue too, we're trying to do a silent renew via an iframe, it doesn't seem to matter what the settings but it triggers it every 2 seconds and occasionally I get the error mentioned.

**Comment by shaunluttin** [comment]
@mttmccb Thanks for bumping this issue. I've been meaning to implement silent renew in this plugin. Once I've done that, I will probably run into the problem that this issue mentions, and will then find a way to resolve it.

**Comment by shaunluttin** [comment]
@mttmccb @bewl https://github.com/shaunluttin/aurelia-open-id-connect/commit/fdb1115e01b34d8b515d1097aec8492ba9c17d43 may have resolved this. Time permitting, please try your use case with version `0.10.1`. I would appreciate that.

**Comment by mttmccb** [comment]
I still get the error but it seems to only occur the first time

**Comment by shaunluttin** [comment]
@mttmccb Well, that's an improvement. It would be good to now what is causing it the first time too. I will see if I can recreate the error on my side.

**Comment by shaunluttin** [comment]
@mttmccb I have not been able to recreate the error on my side. Could you please tell me more about your setup. 

> ...we're trying to do a silent renew via an iframe, it doesn't seem to matter what the settings but it triggers it every 2 seconds and occasionally I get the error mentioned.

I've tried the same thing with the /demo project in release `0.10.1`. Would you be willing to run that demo against your Open ID Connect server and then let me know whether you have the issue there too. That would help a great deal to isolate the error.

**Comment by mttmccb** [comment]
I'll hopefully get to this tomorrow.

**Comment by mttmccb** [comment]
Sorry for the delay, I'm still getting the error, trying to work out if it's a config error or not.

This is the line it fails as, as far as I can tell `contentWindow` is null so `postMessage` fails.

```
e._frame.contentWindow.postMessage(e._client_id + " " + e._session_state, e._frame_origin)
````

**Comment by mttmccb** [comment]
An reason for using this one? It's using 1.2.2 (the latest) and using this fork means it's locked to 1.2.0

```
    "oidc-client": "github:shaunluttin/oidc-client-js#master"
```

**Comment by shaunluttin** [comment]
> An reason for using this one?

@mttmccb I'm using my own fork of oidc-client-js, because it has a better TypeScript definition file.

**Comment by shaunluttin** [comment]
Here are two things that I would try. 
1. Increase `checkSessionInterval` to `10000`.
2. Increase `silentRequestTimeout` to `10000`.

**Comment by mttmccb** [comment]
Both of those are already set to 10000, it works intermittently, if it works I get a console message every 2 seconds saying 

```
unchanged message from check session op iframe
```

I think it's related to caching but I haven't been able to reliably replicate it.

**Comment by shaunluttin** [comment]
@mttmccb Is your source code open for me to clone and try on my machine?

**Comment by mttmccb** [comment]
It isn't but I can make a repo when I'm in tomorrow, I just based it on the demo with our id server

**Comment by mttmccb** [comment]
Sorry I haven't had time to do the repo, I'll looked into and updated to the latest versions but still experiencing the problem. I've made very few changes but it's not clear why it's occurring. I'm using Chrome on Mac

**Comment by AndreSteenbergen** [comment]
We don't really need the iframe I guess. To shut oidc client up, just add these to the parameters:
```
automaticSilentRenew : false,
monitorSession : false,
```
It might be nice for the connector to override these in the code, the connector can already track the session itself, see the demo for that.

**Comment by stuartbloom** [comment]
I think this can be fixed by looking here: https://github.com/IdentityModel/oidc-client-js/issues/171

**Comment by MJunghenn** [comment]
What is the fix for this? 
I need to monitor and renew the session, i can't just disable it for my project.

**Comment by shaunluttin** [comment]
@MJunghenn Apologies that I do not have a fix for this at the time. I have unfortunately been busy with other projects.

**Comment by mttmccb** [comment]
It's already referenced above, the fix appears to be the use a container other than the body for your application. https://github.com/IdentityModel/oidc-client-js/issues/171

**Comment by shaunluttin** [comment]
@mttmccb Thank you for tracking down the fix!

I have now added the fix to the demo applications here: 

https://github.com/shaunluttin/aurelia-open-id-connect-demos/tree/master/aurelia-app-identity-server

I have also added the fix to the documentation here: 

https://github.com/shaunluttin/aurelia-open-id-connect#change-the-aurelia-container

**Comment by mttmccb** [comment]
Good one to fix :)
