### ISSUE TITLE
Handle page refresh after the authorization server redirects back to the app.

### ISSUE THREAD

**Issue by shaunluttin** [shaunluttin/aurelia-open-id-connect#46]
Steps to reproduce: 

1. git clone git@github.com:shaunluttin/aurelia-open-id-connect-demos.git
1. cd aurelia-app
1. npm install
1. npm run demo
1. Open a web browser to localhost:9000
1. Click log in and log in at the OpenID Connect provider.
1. Confirm that the redirect is to localhost:9000/private
1. Refresh the page.

Actual behavior: 

The page refreshes to http://localhost:9000/signin-oidc#id_token=eyJ0eX....AiOiJ

Expected behavior: 

The page refreshes to http://localhost:9000/private

**Comment by shaunluttin** [comment]
This is the navigation instruction that causes the problem. 

    const navigationInstruction = () => {
      instruction.config.redirect =
        this.openIdConnectConfiguration.loginRedirectRoute;
    };

https://github.com/shaunluttin/aurelia-open-id-connect/blob/master/src/open-id-connect-navigation-strategies.ts#L29

That navigation instruction updates the web browser's location but does not update the web browser's history (or "page to refresh").

**Comment by shaunluttin** [comment]
\cc @AndreSteenbergen Any ideas on how to resolve this? I am not sure how to make the Aurelia router update the page that the web browser will load on refresh.

**Comment by shaunluttin** [comment]
It looks like using `window.location.href = "foobar"` works.

**Comment by shaunluttin** [comment]
`window.location.assign("path")` seems the most appropriate.

**Comment by AndreSteenbergen** [comment]
I agree, assigning is more appropriate, sorry for not seeing this sooner, I was asleep.

**Comment by shaunluttin** [comment]
@AndreSteenbergen What? Sleeping!? Inexcusable. ;-)
