### ISSUE TITLE
A paragraph or two to describe the added values of this adapter over using it directly?

### ISSUE THREAD

**Issue by jack4it** [shaunluttin/aurelia-open-id-connect#6]
1. What are the added values of this add-in?
2. Can we not use that oidc library directly on top of Aurelia?

**Comment by shaunluttin** [comment]
> What are the added values of this add-in?
I'm not sure myself. :) 

> Can we not use that oidc library directly on top of Aurelia?
My sense is that yes we can.

**Comment by shaunluttin** [comment]
@jack4it I've given this some more thought. I think the main value added is the handling of routing. The plugin fundamentally adapts the oidc-client-js to the Aurelia router.
