### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by mttmccb** [shaunluttin/aurelia-open-id-connect#7]
I'm running into an an issue with webpack, it doesn't look like it's importing the HTML template too as it can't find `open-id-connect-user-block`, any ideas how to adjust the config?

**Comment by mttmccb** [comment]
I've tried a few of the options in [aurelia-webpack-plugin](https://github.com/aurelia/webpack-plugin) but no joy so far.

**Comment by shaunluttin** [comment]
@mttmccb I'm afraid I do not have any experience using WebPack. I do recall experiencing some frustration myself with having the HTML templates work. Does the demo project work for you? 

```
git clone https://github.com/shaunluttin/aurelia-open-id-connect.git
cd aurelia-open-id-connect/demo
npm install -y
npm run demo
```

**Comment by shaunluttin** [comment]
@mttmccb I just read my own README.md. 

> Set `build.loader.plugs.stub = false` in aurelia.json to load HTML from the package.

**Comment by mttmccb** [comment]
Can't get past that step, I'm getting a script error in main.js, I can't see any obvious erorrs though...

Once [this issue](https://github.com/aurelia/skeleton-navigation/issues/688) has been resolved I'll try webpack again, hopefully early next week.

**Comment by mttmccb** [comment]
For the webpack project there is no aurelia.json, I suspect the changes I'm making aren't working as I don't know how to change easy-webpack to do what I want it to.

**Comment by shaunluttin** [comment]
@mttmccb Thank you for the update. It would be great to have this plugin working with all the major package managers that Aurelia supports.

**Comment by mttmccb** [comment]
After switching to a more standard webpack setup I was able to include the missing resources by adding this into my `packages.json`

```
  "aurelia": {
    "build": {
      "resources": [
        "aurelia-notification",
        "aurelia-i18n",
        "aurelia-animator-css",
        "aurelia-open-id-connect",
        "aurelia-open-id-connect/open-id-connect-user-block",
        "aurelia-open-id-connect/open-id-connect-role-filter"
      ]
    }
  },
```

**Comment by shaunluttin** [comment]
@mttmccb Thank you for the update. I appreciate that. That will help me to support WebPack with this plugin. I will close this issue. Thank you for your contribution, and please add other issues if you have any questions about using the plugin.
